---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-ground
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: dvojsffxf
  CLOUDINARY_KEY: 591578613813726
  CLOUDINARY_SECRET: rN_04FUlc0A8Ubjotr1yI7gjNAk
  MAPBOX_TOKEN: pk.eyJ1IjoibWFubGluZXJvb3QxMiIsImEiOiJjbTY5azE3cHEwYWd4MmpzaDZzdWY0ZTloIn0.o_rEw9K6gZQ21zZ3OIjPyQ
  DB_URL: mongodb+srv://mdb_sa_id_67977ed572f1a57c5ed16ed2:mdb_sa_sk_PlZH9w8CwPYGrzTXl7UAQoNFRIsC83ur3XouyjFn@3-tier-app.jiy49.mongodb.net/?retryWrites=true&w=majority&appName=3-tier-app
  SECRET: MAHESH

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: manlineroot12/campground:5
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer